"""Initial migration

Revision ID: c08785713a09
Revises: 
Create Date: 2026-03-20 20:27:17.669248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08785713a09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careplan_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_token', sa.String(length=255), nullable=False),
    sa.Column('careplan_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('careplan_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_careplan_cache_receipt_token'), ['receipt_token'], unique=True)

    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('submission_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('receipt_token', sa.String(length=255), nullable=False),
    sa.Column('provider_guid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('submission_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_receipts_provider_guid'), ['provider_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_receipts_receipt_token'), ['receipt_token'], unique=False)

    op.create_table('task_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('receipt_token', sa.String(length=255), nullable=False),
    sa.Column('provider_guid', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('payload_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('task_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_audit_log_provider_guid'), ['provider_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_audit_log_receipt_token'), ['receipt_token'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('provider_guid', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_guid'], ['providers.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_provider_guid'), ['provider_guid'], unique=False)

    op.create_table('provider_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('receipt_token', sa.String(length=255), nullable=False),
    sa.Column('provider_guid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('patient_guid', sa.String(length=36), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('careplan_guid', sa.String(length=36), nullable=True),
    sa.Column('careplan_title', sa.String(length=255), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_guid'], ['providers.guid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    with op.batch_alter_table('provider_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_tasks_provider_guid'), ['provider_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_tasks_receipt_token'), ['receipt_token'], unique=True)

    op.create_table('inbound_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('request_guid', sa.String(length=36), nullable=False),
    sa.Column('provider_guid', sa.String(length=36), nullable=False),
    sa.Column('receipt_token', sa.String(length=255), nullable=False),
    sa.Column('careplan_json', sa.JSON(), nullable=False),
    sa.Column('fhir_resource', sa.JSON(), nullable=True),
    sa.Column('patient_guid', sa.String(length=36), nullable=True),
    sa.Column('contract_guid', sa.String(length=36), nullable=True),
    sa.Column('grant_token', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_status', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('request_guid')
    )
    with op.batch_alter_table('inbound_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_requests_request_guid'), ['request_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_requests_provider_guid'), ['provider_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_requests_receipt_token'), ['receipt_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_requests_patient_guid'), ['patient_guid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_requests_patient_guid'))
        batch_op.drop_index(batch_op.f('ix_inbound_requests_receipt_token'))
        batch_op.drop_index(batch_op.f('ix_inbound_requests_provider_guid'))
        batch_op.drop_index(batch_op.f('ix_inbound_requests_request_guid'))

    op.drop_table('inbound_requests')
    with op.batch_alter_table('provider_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_tasks_receipt_token'))
        batch_op.drop_index(batch_op.f('ix_provider_tasks_provider_guid'))

    op.drop_table('provider_tasks')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_provider_guid'))

    op.drop_table('api_keys')
    with op.batch_alter_table('task_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_audit_log_receipt_token'))
        batch_op.drop_index(batch_op.f('ix_task_audit_log_provider_guid'))

    op.drop_table('task_audit_log')
    with op.batch_alter_table('submission_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_receipts_receipt_token'))
        batch_op.drop_index(batch_op.f('ix_submission_receipts_provider_guid'))

    op.drop_table('submission_receipts')
    op.drop_table('providers')
    with op.batch_alter_table('careplan_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_careplan_cache_receipt_token'))

    op.drop_table('careplan_cache')
    # ### end Alembic commands ###
